### ISSUE TITLE
Error: You are accessing SWNRBaseItem#data which has been migrated to SWNRBaseItem#system

### ISSUE THREAD

**Issue by Novabella** [wintersleepAI/foundry-swnr#55]
`Error: You are accessing SWNRBaseItem#data which has been migrated to SWNRBaseItem#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:1993:19)
    at SWNRBaseItem._logDataFieldMigration (commons.js:8429:14)
    at Object.get (commons.js:8393:18)
    at character.ts:173:39
    at EmbeddedCollection.filter (commons.js:4103:14)
    at SWNRCharacterActor.prepareDerivedData (character.ts:173:18)
    at SWNRCharacterActor.prepareData (foundry.js:14126:12)
    at SWNRCharacterActor._safePrepareData (foundry.js:14101:14)
    at SWNRCharacterActor._initialize (foundry.js:13929:19)
    at new DataModel (commons.js:6817:12)`

This warning floods my console every time I launch the world using this system. I'm concerned with updating to the next update, as it says this backwards compat will be removed in v12, I don't wanna run the risk of borking my world file again with an update.

**Comment by wintersleepAI** [comment]
Working on getting things working for v11 currently. Hopefully the latest test release fixes a major issue.

the WWN dev and I are talking about making a new unified system (with the ability to migrate worlds to it). If it ends going this way, that system would be made compatible for v12+13 and not this one. If we don't I will get around to fixing it for v12.  whenever v12 comes out do not upgrade to it right away, most system and module developers are pretty slow on getting things compatible.
